### ISSUE TITLE
Angular 16 - library is not compatible with Angular Ivy

### ISSUE THREAD

**Issue by mdudek** [danielmoncada/date-time-picker-dayjs-adapter#7]
node_modules/@danielmoncada/angular-datetime-picker-dayjs-adapter/lib/dayjs-adapter/dayjs-date-time.module.d.ts:6:22

This likely means that the library (@danielmoncada/angular-datetime-picker-dayjs-adapter) which declares OwlDayJsDateTimeModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by danielmoncada** [comment]
updated: https://github.com/danielmoncada/date-time-picker-dayjs-adapter/pull/8

**Comment by mdudek** [comment]
Unfortunately, the issue is not resolved by new version 2.0.1, it still throws 'library is not compatible with Angular Ivy'.
